run:
  deadline: 5m
  build-tags:
    - debugdemoinfocs
  skip-dirs:
    - msg
  skip-files:
    - parser_interface.go
    - game_state_interface.go
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - exportloopref
    - exhaustive
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - asciicheck
    - gocognit
    - godox
    - nestif
    - prealloc
    - revive
    - wsl

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - wsl
        - funlen

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  gci:
    local-prefixes: github.com/markus-wa/demoinfocs-golang/v5
