language: go

go:
  - 1.8
  - master

script:
  - go test -v -race -coverprofile=coverage.txt -coverpkg=$(go list ./... | grep -v msg | awk -vORS=, '{ print $1 }' | sed 's/,$/\n/')

after_success:
  - bash <(curl -s https://codecov.io/bash)
